import type { Context } from "@steve.kite/stdlib";

import type { Compute } from "../../compute/Compute.js";
import { computePermissionsForContext } from "../../compute/impl/computePermissionsForContext.js";
import type { FileReadLog } from "../../compute/impl/FileReadLog.js";
import { parentComputePath, resolveComputePath } from "../../compute/impl/resolveComputePath.js";

/**
 * Put generated bytes on the agent's machine.
 *
 * The read guard is taken again here rather than trusted from before the generation, because a
 * long generation gives whoever else is working on that file plenty of time to save it. Missing
 * directories are created, and the finished file counts as read: the agent knows exactly what it
 * holds, so a following write of the same path is not working blind.
 */
export async function writeGeneratedMediaFile(
    compute: Compute,
    reads: FileReadLog,
    ctx: Context,
    path: string,
    bytes: Uint8Array,
): Promise<string> {
    const permissions = computePermissionsForContext(ctx);
    const resolvedPath = resolveComputePath(path, compute.cwd, compute.fs.home);
    await reads.assertRead(ctx, compute.fs, permissions, resolvedPath);
    const parent = parentComputePath(resolvedPath);
    if (parent !== resolvedPath) {
        await compute.fs.mkdir(permissions, parent, { recursive: true });
    }
    await compute.fs.writeFile(permissions, resolvedPath, bytes);
    await reads.record(
        ctx,
        resolvedPath,
        (await compute.fs.stat(permissions, resolvedPath)).mtimeMs,
    );
    return resolvedPath;
}
