export { createHappyPluginClient, HappyPluginApiError } from "./createHappyPluginClient.js";
export { createHappyPluginClient as connectHappy } from "./createHappyPluginClient.js";
export { createHappyMcpToolName, normalizeHappyMcpName } from "./createHappyMcpToolName.js";
export { happyMcpCompletionToResult } from "./happyMcpCompletionToResult.js";
export {
    assertHappyPluginStorageKey,
    assertHappyPluginStorageQuota,
    decodeHappyPluginStorageValue,
    encodeHappyPluginStorageValue,
} from "./pluginAppStorage.js";
export {
    happyPluginAppResourceMediaType,
    isHappyPluginImageMediaType,
} from "./pluginAppResources.js";
export {
    createHappyPluginTestHost,
    type CreateHappyPluginTestHostOptions,
    type HappyPluginTestHost,
} from "./createHappyPluginTestHost.js";
export { defineMcpTool } from "./startHappyMcpServer.js";
export { Type } from "@sinclair/typebox";
export type { Static, TSchema } from "@sinclair/typebox";
export type {
    AgentMessageDelivery,
    ArchiveWorkspaceInput,
    CreateHappyPluginClientOptions,
    CreateSessionInput,
    CreateWorkspaceInput,
    HappyPlugin,
    HappyPluginClient,
    HappyPluginAppContribution,
    HappyPluginAppManifest,
    HappyPluginManifest,
    HappyPluginState,
    HappyPluginVersion,
    HappyPluginAppResourceSummary,
    HappyPluginAppSidebar,
    HappyPluginAppToolSummary,
    HappyPluginResourceMediaType,
    HappyMcpCallCompletion,
    HappyMcpContent,
    HappyMcpEvent,
    HappyMcpInputSchema,
    HappyMcpServer,
    HappyMcpServerRegistration,
    HappyMcpServerStatus,
    HappyMcpTool,
    HappyMcpToolContext,
    HappyMcpToolRegistration,
    HappyMcpToolResult,
    HappyPluginTestRequest,
    HappyPluginTestSeed,
    HappyProject,
    HappyProviderUsage,
    HappyProviderUsageCredits,
    HappyProviderUsageEntry,
    HappyProviderUsageWindow,
    HappySession,
    HappyWorkspace,
    HappyWorkspaceStatus,
    ListWorkspacesInput,
    RenameWorkspaceInput,
    SendAgentMessageInput,
    StartHappyMcpServerOptions,
} from "./types.js";
export {
    agentMessageDeliverySchema,
    archiveWorkspaceBodySchema,
    archiveWorkspaceInputSchema,
    createHappyPluginClientOptionsSchema,
    createSessionInputSchema,
    createWorkspaceBodySchema,
    createWorkspaceInputSchema,
    happyProjectSchema,
    happyPluginAppContributionSchema,
    happyPluginAppIdSchema,
    happyPluginAppManifestSchema,
    happyPluginManifestSchema,
    happyPluginVersionSchema,
    happyPluginAppResourceSummarySchema,
    happyPluginAppSidebarSchema,
    happyPluginAppToolSummarySchema,
    happyPluginResourceMediaTypeSchema,
    happyPluginResourcePathSchema,
    happyPluginResourceUriSchema,
    happyPluginSchema,
    happyPluginStateSchema,
    happyProviderUsageCreditsSchema,
    happyProviderUsageEntrySchema,
    happyProviderUsageSchema,
    happyProviderUsageWindowSchema,
    happyMcpCallCompletionSchema,
    happyMcpCallEventSchema,
    happyMcpCancelEventSchema,
    happyMcpContentSchema,
    happyMcpEventSchema,
    happyMcpImageContentSchema,
    happyMcpInputSchemaSchema,
    happyMcpServerRegistrationSchema,
    happyMcpTextContentSchema,
    happyMcpToolRegistrationSchema,
    happyMcpToolResultSchema,
    happyPluginTestRequestSchema,
    happyPluginTestSeedSchema,
    happySessionSchema,
    happyWorkspaceSchema,
    happyWorkspaceStatusSchema,
    listProjectsResponseSchema,
    listHappyProviderUsageResponseSchema,
    listPluginsResponseSchema,
    listSessionsResponseSchema,
    listWorkspacesInputSchema,
    listWorkspacesResponseSchema,
    renameWorkspaceInputSchema,
    renameWorkspaceBodySchema,
    registerHappyMcpServerResponseSchema,
    sendAgentMessageInputSchema,
    sendAgentMessageBodySchema,
    sessionResponseSchema,
    workspaceResponseSchema,
} from "./types.js";
export {
    HAPPY_PLUGIN_MAX_APPS,
    HAPPY_PLUGIN_MAX_APP_BYTES,
    HAPPY_PLUGIN_MAX_APP_RESOURCES,
    HAPPY_PLUGIN_MAX_LIST_ITEMS,
    HAPPY_PLUGIN_MAX_RESOURCE_BYTES,
    HAPPY_PLUGIN_MAX_STORAGE_BYTES,
    HAPPY_PLUGIN_MAX_STORAGE_KEYS,
    HAPPY_PLUGIN_MAX_STORAGE_VALUE_BYTES,
} from "./types.js";

import { createHappyPluginClient } from "./createHappyPluginClient.js";

/** The plugin's ready-to-use connection to its owning Happy daemon. */
export const happy = createHappyPluginClient();
