export { createHappyPluginClient, HappyPluginApiError } from "./createHappyPluginClient.js";
export { createHappyPluginClient as connectHappy } from "./createHappyPluginClient.js";
export { createHappyMcpToolName, normalizeHappyMcpName } from "./createHappyMcpToolName.js";
export { happyMcpCompletionToResult } from "./happyMcpCompletionToResult.js";
export {
    createHappyPluginTestHost,
    type CreateHappyPluginTestHostOptions,
    type HappyPluginTestHost,
} from "./createHappyPluginTestHost.js";
export { defineMcpTool } from "./startHappyMcpServer.js";
export {
    defineHappyPluginApplicationAction,
    startHappyPluginApplication,
} from "./startHappyPluginApplication.js";
export { Type } from "@sinclair/typebox";
export type { Static, TSchema } from "@sinclair/typebox";
export type {
    AgentMessageDelivery,
    ArchiveWorkspaceInput,
    CreateHappyPluginClientOptions,
    CreateSessionInput,
    CreateWorkspaceInput,
    HappyPluginClient,
    HappyPluginApplication,
    HappyPluginApplicationAction,
    HappyPluginApplicationActionCompletion,
    HappyPluginApplicationActionContext,
    HappyPluginApplicationContribution,
    HappyPluginApplicationEvent,
    HappyPluginApplicationNavigation,
    HappyPluginApplicationRegistration,
    HappyPluginApplicationResource,
    HappyPluginApplicationResourceSummary,
    HappyPluginApplicationStatus,
    HappyPluginResourceMediaType,
    HappyMcpCallCompletion,
    HappyMcpContent,
    HappyMcpEvent,
    HappyMcpInputSchema,
    HappyMcpServer,
    HappyMcpServerRegistration,
    HappyMcpServerStatus,
    HappyMcpTool,
    HappyMcpToolContext,
    HappyMcpToolRegistration,
    HappyMcpToolResult,
    HappyPluginTestRequest,
    HappyPluginTestSeed,
    HappyProject,
    HappyProviderUsage,
    HappyProviderUsageCredits,
    HappyProviderUsageEntry,
    HappyProviderUsageWindow,
    HappySession,
    HappyWorkspace,
    HappyWorkspaceStatus,
    ListWorkspacesInput,
    RenameWorkspaceInput,
    SendAgentMessageInput,
    StartHappyMcpServerOptions,
    StartHappyPluginApplicationOptions,
} from "./types.js";
export {
    agentMessageDeliverySchema,
    archiveWorkspaceBodySchema,
    archiveWorkspaceInputSchema,
    createHappyPluginClientOptionsSchema,
    createSessionInputSchema,
    createWorkspaceBodySchema,
    createWorkspaceInputSchema,
    happyProjectSchema,
    happyPluginApplicationActionCancelEventSchema,
    happyPluginApplicationActionCompletionSchema,
    happyPluginApplicationActionRequestEventSchema,
    happyPluginApplicationContributionSchema,
    happyPluginApplicationEventSchema,
    happyPluginApplicationIdSchema,
    happyPluginApplicationNavigationSchema,
    happyPluginApplicationRegistrationSchema,
    happyPluginApplicationResourceSchema,
    happyPluginApplicationResourceSummarySchema,
    happyPluginResourceMediaTypeSchema,
    happyPluginResourcePathSchema,
    happyProviderUsageCreditsSchema,
    happyProviderUsageEntrySchema,
    happyProviderUsageSchema,
    happyProviderUsageWindowSchema,
    happyMcpCallCompletionSchema,
    happyMcpCallEventSchema,
    happyMcpCancelEventSchema,
    happyMcpContentSchema,
    happyMcpEventSchema,
    happyMcpImageContentSchema,
    happyMcpInputSchemaSchema,
    happyMcpServerRegistrationSchema,
    happyMcpTextContentSchema,
    happyMcpToolRegistrationSchema,
    happyMcpToolResultSchema,
    happyPluginTestRequestSchema,
    happyPluginTestSeedSchema,
    happySessionSchema,
    happyWorkspaceSchema,
    happyWorkspaceStatusSchema,
    listProjectsResponseSchema,
    listHappyProviderUsageResponseSchema,
    listSessionsResponseSchema,
    listWorkspacesInputSchema,
    listWorkspacesResponseSchema,
    renameWorkspaceInputSchema,
    renameWorkspaceBodySchema,
    registerHappyMcpServerResponseSchema,
    registerHappyPluginApplicationResponseSchema,
    sendAgentMessageInputSchema,
    sendAgentMessageBodySchema,
    sessionResponseSchema,
    workspaceResponseSchema,
} from "./types.js";
export {
    HAPPY_PLUGIN_MAX_APPLICATIONS,
    HAPPY_PLUGIN_MAX_APPLICATION_ACTIONS,
    HAPPY_PLUGIN_MAX_APPLICATION_RESOURCES,
    HAPPY_PLUGIN_MAX_APPLICATION_RESOURCE_BYTES,
    HAPPY_PLUGIN_MAX_RESOURCE_BYTES,
} from "./types.js";

import { createHappyPluginClient } from "./createHappyPluginClient.js";

/** The plugin's ready-to-use connection to its owning Happy daemon. */
export const happy = createHappyPluginClient();
