import { sql } from "drizzle-orm";

import type { SessionDatabase } from "../openSessionDatabase.js";

const statements = [
    `CREATE TABLE project_avatar_assets (
        hash TEXT NOT NULL PRIMARY KEY,
        media_type TEXT NOT NULL,
        byte_length INTEGER NOT NULL,
        width INTEGER NOT NULL,
        height INTEGER NOT NULL,
        created_at_ms INTEGER NOT NULL,
        dereferenced_at_ms INTEGER
    )`,
    `CREATE TABLE projects (
        id TEXT NOT NULL PRIMARY KEY,
        path TEXT NOT NULL UNIQUE,
        storage_key TEXT NOT NULL COLLATE NOCASE UNIQUE,
        kind TEXT NOT NULL,
        name TEXT NOT NULL,
        name_key TEXT NOT NULL UNIQUE,
        name_source TEXT NOT NULL,
        order_key TEXT NOT NULL COLLATE BINARY,
        avatar_hash TEXT REFERENCES project_avatar_assets(hash),
        avatar_source TEXT,
        initialization_status TEXT NOT NULL,
        initialization_error TEXT,
        initialization_attempt INTEGER NOT NULL,
        presence TEXT NOT NULL,
        worktree_support TEXT NOT NULL,
        worktree_support_reason TEXT,
        git_branch TEXT,
        git_head TEXT,
        git_upstream TEXT,
        git_ahead INTEGER NOT NULL,
        git_behind INTEGER NOT NULL,
        git_detached INTEGER NOT NULL,
        version INTEGER NOT NULL,
        created_at_ms INTEGER NOT NULL,
        updated_at_ms INTEGER NOT NULL,
        archived_at_ms INTEGER
    )`,
    `CREATE TABLE project_workspaces (
        id TEXT NOT NULL PRIMARY KEY,
        project_id TEXT NOT NULL REFERENCES projects(id),
        path TEXT NOT NULL UNIQUE,
        storage_key TEXT NOT NULL COLLATE NOCASE,
        name TEXT NOT NULL,
        name_key TEXT NOT NULL,
        title TEXT,
        order_key TEXT NOT NULL COLLATE BINARY,
        kind TEXT NOT NULL,
        status TEXT NOT NULL,
        base_ref TEXT,
        base_commit TEXT,
        git_common_dir TEXT NOT NULL,
        error TEXT,
        client_request_id TEXT,
        creator_session_id TEXT,
        presence TEXT NOT NULL,
        git_branch TEXT,
        git_head TEXT,
        git_upstream TEXT,
        git_ahead INTEGER NOT NULL,
        git_behind INTEGER NOT NULL,
        git_detached INTEGER NOT NULL,
        version INTEGER NOT NULL,
        created_at_ms INTEGER NOT NULL,
        updated_at_ms INTEGER NOT NULL,
        archived_at_ms INTEGER,
        UNIQUE (project_id, storage_key),
        UNIQUE (project_id, name_key),
        UNIQUE (project_id, client_request_id)
    )`,
    `CREATE TABLE sessions (
        id TEXT NOT NULL PRIMARY KEY,
        agent_id TEXT NOT NULL,
        project_id TEXT NOT NULL REFERENCES projects(id),
        workspace_id TEXT REFERENCES project_workspaces(id),
        order_key TEXT NOT NULL COLLATE BINARY,
        session_kind TEXT NOT NULL,
        parent_session_id TEXT,
        root_session_id TEXT NOT NULL,
        depth INTEGER NOT NULL,
        parent_tool_call_id TEXT,
        task_name TEXT,
        description TEXT,
        archived INTEGER NOT NULL,
        track_unread INTEGER NOT NULL,
        unread_reason TEXT,
        unread_since_ms INTEGER,
        cwd TEXT NOT NULL,
        draft TEXT,
        draft_updated_at_ms INTEGER,
        docker_json TEXT,
        secret_ids_json TEXT NOT NULL,
        provider_id TEXT NOT NULL,
        model_id TEXT NOT NULL,
        effort TEXT,
        service_tier TEXT,
        instructions TEXT,
        append_system_prompt TEXT,
        system_prompt TEXT,
        external_tools_json TEXT NOT NULL,
        durable_skills_json TEXT NOT NULL,
        status TEXT NOT NULL,
        active_run_id TEXT,
        active_since_ms INTEGER,
        elapsed_ms INTEGER NOT NULL,
        total_tokens INTEGER NOT NULL,
        session_token_count_json TEXT,
        usage_json TEXT,
        last_event_id TEXT,
        permission_mode TEXT NOT NULL,
        models_json TEXT NOT NULL,
        tools_json TEXT NOT NULL,
        tasks_json TEXT NOT NULL,
        workflows_json TEXT NOT NULL,
        workflows_enabled INTEGER NOT NULL,
        goal_json TEXT,
        next_task_id INTEGER NOT NULL,
        title TEXT,
        title_status TEXT NOT NULL,
        title_error TEXT,
        recap TEXT,
        metadata_updated_at_ms INTEGER,
        metadata_run_id TEXT,
        interrupted INTEGER NOT NULL,
        interruption_json TEXT,
        last_message_at_ms INTEGER,
        created_at_ms INTEGER NOT NULL,
        updated_at_ms INTEGER NOT NULL
    )`,
    `CREATE TABLE session_events (
        seq INTEGER PRIMARY KEY AUTOINCREMENT,
        session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
        event_id TEXT NOT NULL UNIQUE,
        type TEXT NOT NULL,
        created_at_ms INTEGER NOT NULL,
        data_json TEXT NOT NULL,
        run_id TEXT,
        message_id TEXT,
        tool_call_id TEXT
    )`,
    `CREATE TABLE session_messages (
        session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
        position INTEGER NOT NULL,
        message_id TEXT NOT NULL,
        role TEXT NOT NULL,
        is_partial INTEGER NOT NULL,
        run_id TEXT,
        message_json TEXT NOT NULL,
        updated_at_ms INTEGER NOT NULL,
        PRIMARY KEY (session_id, position)
    )`,
    `CREATE TABLE session_context_messages (
        session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
        position INTEGER NOT NULL,
        message_id TEXT NOT NULL,
        role TEXT NOT NULL,
        message_json TEXT NOT NULL,
        PRIMARY KEY (session_id, position)
    )`,
    `CREATE TABLE session_turns (
        session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
        run_id TEXT NOT NULL,
        first_position INTEGER NOT NULL,
        PRIMARY KEY (session_id, run_id)
    )`,
    `CREATE TABLE queued_runs (
        session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
        run_id TEXT NOT NULL,
        debug INTEGER NOT NULL,
        debug_directory TEXT,
        display_text TEXT NOT NULL,
        kind TEXT NOT NULL,
        text TEXT NOT NULL,
        user_message_json TEXT NOT NULL,
        integration_config_json TEXT,
        created_at_ms INTEGER NOT NULL,
        PRIMARY KEY (session_id, run_id)
    )`,
    `CREATE TABLE external_tool_calls (
        id TEXT NOT NULL PRIMARY KEY,
        session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
        run_id TEXT NOT NULL,
        batch_id TEXT NOT NULL,
        tool_call_id TEXT NOT NULL,
        provider_tool_call_id TEXT,
        tool_call_index INTEGER NOT NULL,
        definition_json TEXT NOT NULL,
        skill_json TEXT,
        arguments_json TEXT NOT NULL,
        status TEXT NOT NULL,
        resolution_json TEXT,
        consumed INTEGER NOT NULL,
        created_at_ms INTEGER NOT NULL,
        resolved_at_ms INTEGER
    )`,
    `CREATE TABLE durable_user_inputs (
        session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
        request_id TEXT NOT NULL,
        run_id TEXT NOT NULL,
        batch_id TEXT NOT NULL,
        tool_call_id TEXT NOT NULL,
        provider_tool_call_id TEXT,
        tool_call_index INTEGER NOT NULL,
        tool_name TEXT NOT NULL,
        tool_arguments_json TEXT NOT NULL,
        kind TEXT NOT NULL,
        permission_json TEXT,
        request_json TEXT NOT NULL,
        response_json TEXT,
        result_json TEXT,
        status TEXT NOT NULL,
        consumed INTEGER NOT NULL,
        created_at_ms INTEGER NOT NULL,
        resolved_at_ms INTEGER,
        PRIMARY KEY (session_id, request_id)
    )`,
    `CREATE TABLE secret_registrations (
        id TEXT NOT NULL PRIMARY KEY,
        description TEXT NOT NULL,
        environment_json TEXT NOT NULL
    )`,
    `CREATE TABLE secret_environment_variables (
        secret_id TEXT NOT NULL REFERENCES secret_registrations(id) ON DELETE CASCADE,
        normalized_name TEXT NOT NULL,
        name TEXT NOT NULL,
        PRIMARY KEY (secret_id, normalized_name)
    )`,
    `CREATE TABLE project_secret_attachments (
        project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
        secret_id TEXT NOT NULL REFERENCES secret_registrations(id) ON DELETE CASCADE,
        PRIMARY KEY (project_id, secret_id)
    )`,
    `CREATE TABLE happy_sessions (
        session_id TEXT NOT NULL PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE,
        credential_fingerprint TEXT NOT NULL,
        tag TEXT NOT NULL,
        remote_session_id TEXT,
        encryption_variant TEXT NOT NULL,
        encryption_key_base64 TEXT NOT NULL,
        last_remote_seq INTEGER NOT NULL,
        created_at_ms INTEGER NOT NULL,
        updated_at_ms INTEGER NOT NULL
    )`,
    `CREATE TABLE happy_outbox (
        seq INTEGER PRIMARY KEY AUTOINCREMENT,
        session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
        local_id TEXT NOT NULL,
        payload_json TEXT NOT NULL,
        created_at_ms INTEGER NOT NULL,
        UNIQUE (session_id, local_id)
    )`,
    `CREATE TABLE durable_global_events (
        cursor TEXT NOT NULL PRIMARY KEY,
        event_id TEXT NOT NULL UNIQUE,
        aggregate_kind TEXT NOT NULL,
        aggregate_id TEXT NOT NULL,
        type TEXT NOT NULL,
        created_at_ms INTEGER NOT NULL,
        data_json TEXT NOT NULL
    )`,
    `CREATE TABLE durable_global_event_state (
        trimmed_through_cursor TEXT NOT NULL PRIMARY KEY
    )`,
    "CREATE INDEX sessions_agent_id ON sessions(agent_id)",
    "CREATE INDEX session_events_session_seq ON session_events(session_id, seq)",
    "CREATE INDEX session_events_run_id ON session_events(session_id, run_id, seq)",
    "CREATE INDEX session_events_message_id ON session_events(session_id, message_id, seq)",
    "CREATE INDEX session_events_tool_call_id ON session_events(session_id, tool_call_id, seq)",
    "CREATE INDEX session_messages_session_message ON session_messages(session_id, message_id)",
    "CREATE INDEX session_context_messages_session_message ON session_context_messages(session_id, message_id)",
    "CREATE INDEX session_turns_order ON session_turns(session_id, first_position)",
    "CREATE INDEX sessions_parent_created ON sessions(parent_session_id, created_at_ms)",
    "CREATE INDEX sessions_project_activity ON sessions(project_id, last_message_at_ms DESC, updated_at_ms DESC)",
    "CREATE INDEX sessions_workspace_activity ON sessions(workspace_id, last_message_at_ms DESC, updated_at_ms DESC)",
    "CREATE INDEX sessions_parent_order ON sessions(project_id, workspace_id, order_key)",
    "CREATE INDEX projects_updated ON projects(updated_at_ms DESC)",
    "CREATE INDEX projects_order ON projects(order_key)",
    "CREATE INDEX project_workspaces_project_updated ON project_workspaces(project_id, updated_at_ms DESC)",
    "CREATE INDEX project_workspaces_project_order ON project_workspaces(project_id, order_key)",
    "CREATE INDEX external_tool_calls_session_created ON external_tool_calls(session_id, created_at_ms)",
    "CREATE INDEX durable_user_inputs_session_created ON durable_user_inputs(session_id, created_at_ms)",
    "CREATE INDEX happy_outbox_session_seq ON happy_outbox(session_id, seq)",
] as const;

export function init(database: SessionDatabase): void {
    for (const statement of statements) database.run(sql.raw(statement));
}
