export interface SessionUsage {
    /** Complete input context presented to the model, including cached input. */
    readonly input: number;
    /** Tokens generated by the model. */
    readonly output: number;
    /** Cached input tokens, already included in `input`. */
    readonly cacheRead: number;
    /** Newly cached input tokens, already included in `input`. */
    readonly cacheWrite: number;
    /** Complete input context plus generated output. */
    readonly totalTokens: number;
}

export const EMPTY_SESSION_USAGE: SessionUsage = {
    input: 0,
    output: 0,
    cacheRead: 0,
    cacheWrite: 0,
    totalTokens: 0,
};
